language: java
cache:
- ./build/tmp
install:
- gradle setupDecompWorkspace
script:
- gradle build
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "./build/libs/hudtoggler-${TRAVIS_TAG}.jar"
  skip_cleanup: true
  on:
    tags: true